<template>
<div>
    <div>这是A.Vue文件</div>
    <div>这是A.Vue文件</div>
    <div>这是A.Vue文件</div>
    <div>这是A.Vue文件</div>
    <div>这是A.Vue文件</div>
    <div>这是A.Vue文件</div>
    <div>这是A.Vue文件</div>
</div>
</template>